name: "Node Setup"
description: "Sets up a node environment and runs 'npm ci'"
runs:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm ci
